//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library1.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ksiazka
    {
        public int ID_Ksiazki { get; set; }
        public string Nazwa_Ksiazki { get; set; }
        public string Autor_Ksiazki { get; set; }
        public int ID_StanuKsiazki { get; set; }
        public Nullable<int> ID_Wypozyczajacego { get; set; }
    
        public virtual StanKsiazki StanKsiazki { get; set; }
        public virtual Wypozyczajacy Wypozyczajacy { get; set; }
    }
}
